package core

import (
	"context"
)

// Database defines the interface for database operations.
// Implementations should support MySQL, PostgreSQL, or similar relational databases.
type Database interface {
	// Query executes a SELECT query and returns rows.
	Query(ctx context.Context, query string, args ...interface{}) (Rows, error)

	// Exec executes a non-query statement (INSERT, UPDATE, DELETE) and returns a result.
	Exec(ctx context.Context, query string, args ...interface{}) (Result, error)

	// BeginTx starts a new transaction.
	BeginTx(ctx context.Context) (Transaction, error)

	// GetSchema retrieves the schema information for a specific table.
	GetSchema(ctx context.Context, tableName string) (*Schema, error)

	// GetTables returns a list of all table names in the database.
	GetTables(ctx context.Context) ([]string, error)

	// Close closes the database connection and releases resources.
	Close() error
}

// Transaction represents a database transaction.
type Transaction interface {
	// Commit commits the transaction.
	Commit() error

	// Rollback rolls back the transaction.
	Rollback() error

	// Query executes a SELECT query within the transaction.
	Query(query string, args ...interface{}) (Rows, error)

	// Exec executes a non-query statement within the transaction.
	Exec(query string, args ...interface{}) (Result, error)
}

// Rows represents the result set from a database query.
type Rows interface {
	// Next prepares the next result row for reading.
	// Returns false when there are no more rows or an error occurs.
	Next() bool

	// Scan copies the columns in the current row into the values pointed at by dest.
	Scan(dest ...interface{}) error

	// Close closes the rows iterator.
	Close() error

	// Err returns the error, if any, that was encountered during iteration.
	Err() error
}

// Row represents a single row from a database query result.
// This is used for schema translation when reading from the database.
type Row interface {
	// Scan copies the columns in the row into the values pointed at by dest.
	Scan(dest ...interface{}) error
}

// Result represents the result of an Exec operation.
type Result interface {
	// LastInsertId returns the integer generated by the database
	// in response to a command. Typically this will be from an
	// "auto increment" column when inserting a new row.
	LastInsertId() (int64, error)

	// RowsAffected returns the number of rows affected by an
	// update, insert, or delete.
	RowsAffected() (int64, error)
}

